### PR TITLE
Saturation Functions Patch

### LINKED ISSUE #19: Saturation Curves Can Throw Invalid Exception
The RegionOutput function in if97.h correctly throws an exception if a call is made with a (T, p) state that lies "exactly" on the saturation curve, since the vapor/liquid state is not known.  However, the saturation functions also make use of RegionOuput with a calculated saturated temperature, meaning the call is always on the saturation curve.  This should throw an exception (saturated state) even though the desired saturated liquid/vapor state is known and passed as a parameter.

Interestingly, this condition was not observed when compiled with VS2010 on Windows, as the state point was never "exactly" on the saturation curve.  Recent compilation with VS2015, however, threw many exceptions at specific pressure ranges when plotting thermodynamic values along the vapor/liquid saturation curves.  It is expected that optimization differences are the cause and other compilers could behave the same way.

Need to examine the IF97SatState parameter and only throw the exception when neither VAPOR nor LIQUID is specified, as when called by one of the saturation functions.  Otherwise return the correct result for the saturation state specified.

### PR DESCRIPTION
**Pull request by henningjp**
Patch RegionOutput() to correctly handle detection of Region 4 when provided (T, p) state point on the saturation curve from a saturation function that provides the desired vapor/liquid state.  Closes #19.   

In addition:
- [x] Exception for non-saturation function on saturation curve changed to "out_of_range".
- [x] Mathcad wrapper catches a "saturated" condition correctly in all TP wrapper functions.
- [x] Additional error flag in Mathcad wrapper added for "UNKNOWN" exception thrown.

Tested in MinGW and VS compilers for correct behavior of saturation functions.

### CODE REVIEW

File: IF97.h [hunk 1]
```diff
@@ -3919,12 +3919,21 @@ namespace IF97
...
             case REGION_2: if (State == LIQUID)
                                return R1.output(outkey, T, p);  // On saturation curve and need the Liquid phase
                            else
                                return R2.output(outkey, T, p);  // otherwise, use Vapor Region 2
+                           break;
             case REGION_3: return R3.output(outkey, T, p, State);
-            case REGION_4: throw std::invalid_argument("Cannot use Region 4 with T and p as inputs");
+                           break;
+            case REGION_4: if (State == VAPOR)
+                               return R2.output(outkey, T, p);
```
Comment (ibell) [inline IF97.h]: Better here to always add { } to each branch in the conditional - helps to avoid dangling conditional terms

Comment (henningjp) [inline IF97.h]: @ibell ?  The **if** conditional branches, or the **switch** conditional cases, or both?

**Comment by henningjp** [comment]
@ibell - Better?

**Comment by ibell** [comment]
Yes, exactly - you should always wrap branches in conditionals unless it is on one line : https://google.github.io/styleguide/cppguide.html#Conditionals
